apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: java-cicd

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml

# CI sẽ patch field này khi build image mới — đó là cách GitOps đẩy version
# vào cluster mà không cần ai chạy kubectl tay.
images:
  - name: ghcr.io/deepiai112001-svg/java-cicd
    newTag: sha-e972d85
